version: "3.9"

services:
  helloopentelemetry:
    build:
      context: ./src
      dockerfile: Dockerfile
    ports:
      - "5000:8080"
    networks:
      - monitoring
    depends_on:
      - prometheus

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./deploy/prometheus/:/etc/prometheus/
    ports:
      - "9090:9090"
    networks:
      - monitoring

  grafana:
    image: grafana/grafana-oss:latest
    ports:
      - "3000:3000"
    volumes:
      - ./deploy/grafana/config/:/etc/grafana/
      - ./deploy/grafana/dashboards/:/var/lib/grafana/dashboards/
    networks:
      - monitoring
    depends_on:
      - prometheus

networks:
  monitoring:
    driver: bridge
